apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  namespace: default
  annotations:
    backstage.io/managed-by-location: url:https://github.com/ATT-DP10/apm0014514-dcp-workflows/tree/service-workflow/services/scan-multibranch-pipeline-workflow.yaml
    backstage.io/managed-by-origin-location: url:https://github.com/ATT-DP10/apm0014514-dcp-workflows/blob/service-workflow/services/scan-multibranch-pipeline-workflow.yaml
    backstage.io/view-url: https://github.com/ATT-DP10/apm0014514-dcp-workflows/tree/service-workflow/services/scan-multibranch-pipeline-workflow.yaml
    backstage.io/edit-url: https://github.com/ATT-DP10/apm0014514-dcp-workflows/edit/service-workflow/services/scan-multibranch-pipeline-workflow.yaml
    backstage.io/source-location: url:https://github.com/ATT-DP10/apm0014514-dcp-workflows/tree/service-workflow/services/
  name: scan-multibranch-pipeline-workflow
  title: Scan Multibranch Pipeline Workflow
  description: Scan Multibranch Pipeline for given service will be triggered.
  uid: dc8e5783-25a1-410f-b41d-795af2a98e59
  etag: fe8767e53efb603a28d134824350223b1086a9f1
relations:
  - type: ownedBy
    targetRef: group:default/dcp
    target:
      kind: group
      namespace: default
      name: dcp
spec:
  owner: DCP
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - microservice_name
        - team
      properties:
        microservice_name:
          title: Service Name
          type: string
          description: Unique name of the service going to create
          minLength: 3
          maxLength: 50
          pattern: (?!.*-_)(?!.*_-)(?!.*--)(?!.*__)(?!.*-$)(?!.*_$)^[a-zA-Z]+[a-zA-Z0-9-_]*[a-zA-Z0-9-_]+$
          ui:autofocus: true
          ui:help: It should not have ITAP ID in it. It doesnot start with - _ and
            numbers.length should be in between 3 to 60.Name allows only a-z A-Z
            0-9 _ and -Does not allows -- __ -_ and _-Does not allows - and _ at
            end.
        team:
          title: Team Name
          type: string
          description: Enter the name of your team
          ui:field: HarnessProjectPicker
          ui:options:
            allowedKinds:
              - Group
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Triggering Scan Multibranch pipeline in jenkins
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/ow3wOLKoQASF8ih6yBsvAw/all/orgs/DCP/projects/DCPSandbox/pipelines/multibranch_pipeline_test/pipeline-studio/?storeType=REMOTE&connectorRef=account.dcpgithub&repoName=apm0014514-dcp-workflow-pipelines&branch=services&stageId=scan_multibranch&sectionId=OVERVIEW
        inputset:
          service_name: ${{ parameters.microservice_name }}
          team_name: ${{ parameters.team }}
        apikey: ${{ parameters.token }}
        showOutputVariables: true
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
    text:
      - title: Result
        content: ${{ steps.trigger.output.build_result}}
