apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-create-delete-token-with-api-key-secret
  title: Test Create Delete Token with API Key Secret
  description: Test Create Delete Token with API Key Secret
  tags:
    - random
spec:
  owner: user:account/deepesh.kumar@harness.io
  type: service

  parameters:
    - title: Service Details
      required:
        - secret_value
      properties:
        secret_value:
          title: Service Name
          type: string
          description: Mention the project name

  steps:
    - id: trigger
      name: Creating your application
      action: harness:create-secret
      input:
        projectId: Deepesh_CDE
        orgId: default
        secretValue: ${{ parameters.secret_value }}
      apikeySecret: IDPTokenDeepesh

  output:
    links:
      - title: Secret Details
        url: ${{ steps.trigger.output }}
