apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: x-api-key-devspace
  title: Deploy service using x-api-key
  description: A template to Deploy service
spec:
  owner: deepesh.kumar@harness.io
  type: service
  parameters:
    - title: Deploy service
      required:
        - username
      properties:      
        username:
          title: Username
          type: string
        apiKeySecret:  
          title: API Key Secret
          type: string
  steps:
    - id: trigger
      name: Run Deploy service
      action: trigger:harness-custom-pipeline
      input:
        url: https://laxmiharness.pr2.harness.io/ng/account/6cBjZs_fTWCiRITqFyRrgQ/module/cd/orgs/default/projects/Deepesh/pipelines/TriggerViaIDP/pipeline-studio?storeType=INLINE
        inputset:
          "username": ${{ parameters.username }}
        apiKeySecret: ${{ parameters.apiKeySecret }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
