apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: GitSync-demo-variables
  title: GitSync Variable
  description: A template to test GitSync variables
spec:
  owner: deepesh.kumar@harness.io
  type: service
  parameters:
    - title: GitSync Variables
      required:
        - username
        - pipeline.stages.GitsyncStageTemplate.variables.greetings
      properties:
        username:
          title: Username
          type: string
          ui:widget: password
          ui:field: Secret
        harness_project:
          title: Name of your harness project
          type: string
          default: Payments
          description: Name of your project in harness (e.g. Payments, Data)
          ui:field: HarnessProjectPicker  
        techarea:
          title: TechArea
          description: Select the Techarea
          type: string
          ui:field: HarnessAutoOrgPicker          
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
        pipeline.stages.GitsyncStageTemplate.variables.greetings:
          title: Greetings
          type: string
  steps:
    - id: trigger
      name: Writing the GitSync Variable
      action: trigger:harness-custom-pipeline
      input:
        url: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/module/idp-admin/orgs/default/projects/idpprojectsc/pipelines/DummyPipeline/pipeline-studio/?storeType=INLINE&stageId=DummyStage&sectionId=EXECUTION
        inputset: 
          "username": ${{ parameters.username }}
          "pipeline.stages.GitsyncStageTemplate.variables.greetings": ${{ parameters['pipeline.stages.GitsyncStageTemplate.variables.greetings'] }}
        apikey: ${{ parameters.token }}
        enableVariableMapping: true
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
