apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: qaapproval
  title: QA Approval
  description: A template to Deploy service
spec:
  owner: deepesh.kumar@harness.io
  type: service
  parameters:
    - title: Deploy service
      required:
        - username
      properties:      
        username:
          title: Username
          type: string
        apiKeySecret:  
          title: API Key Secret
          type: string
  steps:
    - id: trigger
      name: Run Deploy service
      action: trigger:harness-custom-pipeline
      input:
        url: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/module/cd/orgs/default/projects/Deepesh_CDE/pipelines/testApproval/pipeline-studio?storeType=INLINE
        inputset:
          "username": ${{ parameters.username }}
          "pipeline.variables.data":
             username: ${{ parameters.username }}
        apiKeySecret: ${{ parameters.apiKeySecret }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
