# Edit the template parameters below to see how they will render in the scaffolder form UI
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Infra-Pipeline-TF-community-module
  title: Infra Pipeline TF community module
  description: Automated workflow that provides self service capabilities to provision pipeline with standardized harness template.
  tags:
    - hidden
spec:
  title: Harness Infra Pipeline Provisioner
  owner: UAL_Harness_IDP_PlatformEngineer_DGG
  type: service
  parameters:
  - title: Fill in some steps
# Edit the template parameters below to see how they will render in the scaffolder form UI
parameters:
  - title: Fill in some steps
    required:
      - name
    properties:
      name1:
        title: placeholder Test
        type: string
        description: Unique name of the component
        ui:options:
          placeholder: Sample S3 bucket Name: enz-bucket-name-useast2-dev
      readonlyTest:
        title: Readonly Test
        type: string
        description: Unique name of the component
        default: muni
        ui:readonly: true
      encryptionTypes:
        title: S3 Encryption Types (Existing Key)
        type: boolean
        oneOf:
          - title: Existing Key
            const: true
          - title: New Key
            const: false
        ui:widget: radio
        default: true
steps:
  - id: fetch-base
    name: Fetch Base
    action: fetch:template
    input:
      url: ./template
      values:
        name: ${{parameters.name}}
output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
