apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: abcdef
  title: ABCDEF
  description: A template to Deploy service
spec:
  owner: deepesh.kumar@harness.io
  type: service
  parameters:
    - title: Test service
      properties:
        name1:
          title: placeholder Test
          type: string
          description: Unique name of the component
          ui:placeholder: Sample S3 bucket Name enz-bucket-name-useast2-dev
        readonlyTest:
          title: Readonly Test
          type: string
          description: Unique name of the component
          default: muni
          ui:readonly: true      
        encryptionTypes:
          title: S3 Encryption Types (Existing Key)
          type: boolean
          oneOf:
            - title: Existing Key
              const: true
            - title: New Key
              const: false
          ui:widget: radio
          default: true 
           
  steps:
    - id: trigger
      name: Run Deploy service
      action: trigger:harness-custom-pipeline
      input:
        url: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/all/orgs/default/projects/Deepesh_CDE/pipelines/Idptemplate/pipeline-studio/?storeType=INLINE
        inputset: 
          "name": ${{ parameters.name }}
          "username": ${{ parameters.username }}
          "pipeline.stages.deploy.variables.version": ${{ parameters.version }}
          "pipeline.stages.deploy.spec.execution.steps.ShellScript_1.spec.environmentVariables.scriptVar":  ${{ parameters.username }}
        apiKeySecret: ${{ parameters.apiKeySecret }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
