apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-template
  title: Test Template
  description: A template to test
spec:
  owner: deepesh.kumar@harness.io
  type: service
  parameters:
    - title: Test Template
      properties:
       repositoryname:
         type: string
         ui:field: SelectFieldFromApi
         ui:options:
           title: Select the Name of the repository where your application's source code is stored from the Dropdown List
           description: Enter the Name of the repository where your application's source code is stored
           allowArbitraryValues: true
           path: "proxy/github-repo-search/search/repositories"
           params:
             q: "org:United-Airlines-Org {{parameters.searchTerm}}"
             per_page: "100"
           arraySelector: items
           valueSelector: name
           labelSelector: name
       gittag:
         type: string
         ui:field: SelectFieldFromApi
         ui:options:
           title: Select the Git Tag for your application
           description: Choose the specific tag from the selected repository for compilation and build - CI.
           path: proxy/github-repo-search/repos/United-Airlines-Org/{{parameters.repositoryname}}/tags
           valueSelector: name
           labelSelector: name
    - title: Test Template 1
      properties:
        name:
          type: string
          default: user
  output:
    links:
      - title: Pipeline Details
        zoneVar: ${{ parameters.zone | ui:options.enumMap }}
