apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-template-123
  title: Test Template 1243
  description: A template to Deploy service
spec:
  owner: deepesh.kumar@harness.io
  type: service
  parameters:
    - title: Test Template
      properties:
       name:
         title: Name
         type: string
         description: Unique name of the component
         ui:field: SelectFieldFromApi
         ui:options:
           placeholder: Select titles
           path: proxy/harness-idp-api/ow3wOLKoQASF8ih6yBsvAw/idp/api/catalog/entities/by-uid/a4c60fa0-e642-4d48-be79-4710b1cc44f9
           arraySelector: .
           valueSelector: metadata.name
           setContextData:
             uid: metadata.uid
             account: metadata.aws_account              
       repositoryname:
         type: string
         ui:field: SelectFieldFromApi
         ui:options:
           title: Select the Name of the repository where your application's source code is stored from the Dropdown List
           description: Enter the Name of the repository where your application's source code is stored
           allowArbitraryValues: true
           path: "proxy/github-repo-search/search/repositories"
           params:
             q: "org:United-Airlines-Org {{parameters.searchTerm}}"
             per_page: "100"
           arraySelector: items
           valueSelector: name
           labelSelector: name
       gittag:
         type: string
         ui:field: SelectFieldFromApi
         ui:options:
           title: Select the Git Tag for your application
           description: Choose the specific tag from the selected repository for compilation and build - CI.
           path: proxy/github-repo-search/repos/United-Airlines-Org/{{parameters.repositoryname}}/tags
           valueSelector: name
           labelSelector: name
    - title: Test Template 1
      properties:
        name:
          type: string
          default: user
  steps:
    - id: trigger
      name: Run Deploy service
      action: trigger:harness-custom-pipeline
      input:
        url: https://localhost:8181/ng/account/zEaak-FLS425IEO7OLzMUg/module/cd/orgs/default/projects/Deepesh_CDE/pipelines/Idptemplate/pipeline-studio?storeType=INLINE
        inputset:
          "username": ${{ parameters.username }}
        apiKeySecret: ${{ parameters.apiKeySecret }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}        
